# Generated by c3cdao-ci-scans — reusable Security Gate caller
name: Security Scan

on:
  pull_request:
    branches: {{TRUNK_BRANCHES_YAML}}
  merge_group:
  schedule:
    - cron: "0 13 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  actions: write

jobs:
  security-scan:
    permissions:
      contents: read
      pull-requests: write
      actions: write
    uses: {{CI_SCANS_OWNER}}/{{CI_SCANS_REPO}}/.github/workflows/reusable-security-gate.yml@{{CI_SCANS_REF}}
    # Explicit mapping, not `secrets: inherit` — inherit only works when caller
    # and callee share an org/enterprise; across owners it silently passes
    # nothing. Explicit values evaluate in the caller's context and always work.
    secrets:
      CGR_PULL_TOKEN: ${{ secrets.CGR_PULL_TOKEN }}
      CGR_PULL_USERNAME: ${{ secrets.CGR_PULL_USERNAME }}
      IRONBANK_TOKEN: ${{ secrets.IRONBANK_TOKEN }}
      IRONBANK_USERNAME: ${{ secrets.IRONBANK_USERNAME }}
    with:
      scan_image: {{SCAN_IMAGE}}
      dockerfile: {{DOCKERFILE}}
      builder_image: {{BUILDER_IMAGE}}
      runtime_image: {{RUNTIME_IMAGE}}
      runtime_apks: "{{RUNTIME_APKS}}"
      helm_chart_path: {{HELM_CHART_PATH}}
      helm_values_file: {{HELM_VALUES_FILE}}
      helm_values_local_file: {{HELM_VALUES_LOCAL_FILE}}
      helm_release_name: {{HELM_RELEASE_NAME}}
      cluster_name: {{CLUSTER_NAME}}
      namespace: {{NAMESPACE}}
      secctx_make_target: {{SECCTX_MAKE_TARGET}}
      app_path: {{APP_PATH}}
      app_package: {{APP_PACKAGE}}
      app_module: {{APP_MODULE}}
      app_port: "{{APP_PORT}}"
      require_hardened_bases: {{REQUIRE_HARDENED_BASES}}
      ironbank_builder_image: "{{IRONBANK_BUILDER_IMAGE}}"
      ironbank_runtime_image: "{{IRONBANK_RUNTIME_IMAGE}}"
      extra_build_args: |
        {{EXTRA_BUILD_ARGS}}
